import os
os.chdir(os.path.dirname(os.path.abspath(__file__)))
import sys
sys.path.append("../")
from scripts.optimize import Optimize
from pepcabo.peptide_objective import PeptideObjective
from pepcabo.utils.pep_utils.load_data import load_pairs_train_data, compute_train_zs, initial_peptide_sampling
#import mhcflurry
import torch 
import random

class PeptideOptimization(Optimize):
    """
    Run invbo Optimization for any Sequence Optimization Task using the peptide VAE 

    Args:
        obj: Objective of the optmization
        path_to_peptide_vae_statedict: Path to state dict of pretrained peptide VAE,
        path_to_allele_vae_statedict: Path to state dict of allele peptide VAE,
        max_string_length: Limit on string length that can be generated by VAE (without a limit we can run into OOM issues)
    """
    def __init__(
        self,
        path_to_peptide_vae_statedict,
        path_to_allele_vae_statedict,
        max_string_length: int=400,
        model = None,
        **kwargs
    ):
        self.path_to_peptide_vae_statedict = path_to_peptide_vae_statedict
        self.path_to_allele_vae_statedict = path_to_allele_vae_statedict
        self.max_string_length = max_string_length
        self.model = model
        super().__init__(**kwargs)


        
    def initialize_objective(self):
        self.objective = PeptideObjective(
            obj=self.obj,
            task_id=self.task_id,
            path_to_peptide_vae_statedict=self.path_to_peptide_vae_statedict,
            path_to_allele_vae_statedict=self.path_to_allele_vae_statedict,
            max_string_length=self.max_string_length,
            predictor = self.predictor,
            allele_name=self.allele,
            use_pretrain=self.use_pretrain,
            allele_pscode=self.allele_pscode
        )
        return self
    def init_z(self):
        if self.init_train_z is None:
            self.init_train_z = compute_train_zs(
                self.objective,
                self.init_train_x,
                [self.allele_pscode],
                vanilla=self.vanilla
            )

        return self

    def load_train_data(self,x=None,allele=None):
        ''' Load in or randomly initialize self.num_initialization_points
            total initial data points to kick-off optimization 
            Must define the following:
                self.init_train_x (a list of x's)
                self.init_train_y (a tensor of scores/y's)
                self.init_train_z (a tensor of corresponding latent space points)
            '''
        xs, zs, ys, fos = load_pairs_train_data(
            obj=self.obj,
            num_initialization_points=self.num_initialization_points,
            predictor = self.predictor,
            xs=x,
            allele=allele
        )
        self.init_train_x, self.init_train_z, self.init_train_y, self.init_train_fo = xs, zs, ys, fos
        return self

    def initial_sampling(self,peptide_db, gp_path, guided):
        if (gp_path is not None) and guided:
            out_dict = initial_peptide_sampling(self.objective,[self.allele_pscode],gp_path,self.num_initialization_points,0.2,self.force)
            
            self.init_train_x =  out_dict['decoded_xs'].tolist()
            self.init_train_y = torch.from_numpy(out_dict['scores']).float().unsqueeze(1)
            self.init_train_z = torch.tensor(out_dict['valid_zs']).float()
            self.init_train_fo = torch.tensor(out_dict['fos']).float()

        else:
            peptide_db = peptide_db.peptide.unique().tolist()[:self.num_initialization_points]
            peptide_db = [x for x in peptide_db if not(len(x)<5 or len(x)>15 or ("X" in x) or ("<pad>" in x))]
            random.shuffle(peptide_db)
            return peptide_db